name: dr_tragic_mfa
description: 100% Offline MBBS Quiz & Flashcard App
version: 1.0.0+1
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  sqflite: ^2.3.0
  path: ^1.8.3
  path_provider: ^2.1.1
  fl_chart: ^0.65.0
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
